version: "3.9"

services:
  app:
    build:
      context: ../..
      dockerfile: mlops/docker/Dockerfile.prod
    container_name: ai-ml-snippets-prod
    ports:
      - "8080:8080"
    environment:
      - ENV=production
