version: "3.9"

services:
  app:
    build:
      context: ../..
      dockerfile: mlops/docker/Dockerfile.dev
    container_name: ai-ml-snippets-dev
    volumes:
      - ../..:/app
    ports:
      - "8888:8888"
      - "5000:5000"
    depends_on:
      - qdrant
      - mlflow

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  mlflow:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow
    ports:
      - "5001:5000"
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      BACKEND_STORE_URI: sqlite:///mlflow.db
    volumes:
      - mlflow_data:/mlflow

volumes:
  qdrant_data:
  mlflow_data:
